hoistPattern:
  - '*'
hoistedDependencies:
  '@adiwajshing/keyed-db@0.2.4':
    '@adiwajshing/keyed-db': private
  '@arr/every@1.0.1':
    '@arr/every': private
  '@esbuild/aix-ppc64@0.19.12':
    '@esbuild/aix-ppc64': private
  '@esbuild/android-arm64@0.19.12':
    '@esbuild/android-arm64': private
  '@esbuild/android-arm@0.15.18':
    '@esbuild/android-arm': private
  '@esbuild/android-x64@0.19.12':
    '@esbuild/android-x64': private
  '@esbuild/darwin-arm64@0.19.12':
    '@esbuild/darwin-arm64': private
  '@esbuild/darwin-x64@0.19.12':
    '@esbuild/darwin-x64': private
  '@esbuild/freebsd-arm64@0.19.12':
    '@esbuild/freebsd-arm64': private
  '@esbuild/freebsd-x64@0.19.12':
    '@esbuild/freebsd-x64': private
  '@esbuild/linux-arm64@0.19.12':
    '@esbuild/linux-arm64': private
  '@esbuild/linux-arm@0.19.12':
    '@esbuild/linux-arm': private
  '@esbuild/linux-ia32@0.19.12':
    '@esbuild/linux-ia32': private
  '@esbuild/linux-loong64@0.15.18':
    '@esbuild/linux-loong64': private
  '@esbuild/linux-mips64el@0.19.12':
    '@esbuild/linux-mips64el': private
  '@esbuild/linux-ppc64@0.19.12':
    '@esbuild/linux-ppc64': private
  '@esbuild/linux-riscv64@0.19.12':
    '@esbuild/linux-riscv64': private
  '@esbuild/linux-s390x@0.19.12':
    '@esbuild/linux-s390x': private
  '@esbuild/linux-x64@0.19.12':
    '@esbuild/linux-x64': private
  '@esbuild/netbsd-x64@0.19.12':
    '@esbuild/netbsd-x64': private
  '@esbuild/openbsd-x64@0.19.12':
    '@esbuild/openbsd-x64': private
  '@esbuild/sunos-x64@0.19.12':
    '@esbuild/sunos-x64': private
  '@esbuild/win32-arm64@0.19.12':
    '@esbuild/win32-arm64': private
  '@esbuild/win32-ia32@0.19.12':
    '@esbuild/win32-ia32': private
  '@esbuild/win32-x64@0.19.12':
    '@esbuild/win32-x64': private
  '@eshaz/web-worker@1.2.2':
    '@eshaz/web-worker': private
  '@ffmpeg-installer/darwin-arm64@4.1.5':
    '@ffmpeg-installer/darwin-arm64': private
  '@ffmpeg-installer/darwin-x64@4.1.0':
    '@ffmpeg-installer/darwin-x64': private
  '@ffmpeg-installer/ffmpeg@1.1.0':
    '@ffmpeg-installer/ffmpeg': private
  '@ffmpeg-installer/linux-arm64@4.1.4':
    '@ffmpeg-installer/linux-arm64': private
  '@ffmpeg-installer/linux-arm@4.1.3':
    '@ffmpeg-installer/linux-arm': private
  '@ffmpeg-installer/linux-ia32@4.1.0':
    '@ffmpeg-installer/linux-ia32': private
  '@ffmpeg-installer/linux-x64@4.1.0':
    '@ffmpeg-installer/linux-x64': private
  '@ffmpeg-installer/win32-ia32@4.1.0':
    '@ffmpeg-installer/win32-ia32': private
  '@ffmpeg-installer/win32-x64@4.1.0':
    '@ffmpeg-installer/win32-x64': private
  '@hapi/boom@9.1.4':
    '@hapi/boom': private
  '@hapi/hoek@9.3.0':
    '@hapi/hoek': private
  '@img/sharp-darwin-arm64@0.33.2':
    '@img/sharp-darwin-arm64': private
  '@img/sharp-darwin-x64@0.33.2':
    '@img/sharp-darwin-x64': private
  '@img/sharp-libvips-darwin-arm64@1.0.1':
    '@img/sharp-libvips-darwin-arm64': private
  '@img/sharp-libvips-darwin-x64@1.0.1':
    '@img/sharp-libvips-darwin-x64': private
  '@img/sharp-libvips-linux-arm64@1.0.1':
    '@img/sharp-libvips-linux-arm64': private
  '@img/sharp-libvips-linux-arm@1.0.1':
    '@img/sharp-libvips-linux-arm': private
  '@img/sharp-libvips-linux-s390x@1.0.1':
    '@img/sharp-libvips-linux-s390x': private
  '@img/sharp-libvips-linux-x64@1.0.1':
    '@img/sharp-libvips-linux-x64': private
  '@img/sharp-libvips-linuxmusl-arm64@1.0.1':
    '@img/sharp-libvips-linuxmusl-arm64': private
  '@img/sharp-libvips-linuxmusl-x64@1.0.1':
    '@img/sharp-libvips-linuxmusl-x64': private
  '@img/sharp-linux-arm64@0.33.2':
    '@img/sharp-linux-arm64': private
  '@img/sharp-linux-arm@0.33.2':
    '@img/sharp-linux-arm': private
  '@img/sharp-linux-s390x@0.33.2':
    '@img/sharp-linux-s390x': private
  '@img/sharp-linux-x64@0.33.2':
    '@img/sharp-linux-x64': private
  '@img/sharp-linuxmusl-arm64@0.33.2':
    '@img/sharp-linuxmusl-arm64': private
  '@img/sharp-linuxmusl-x64@0.33.2':
    '@img/sharp-linuxmusl-x64': private
  '@img/sharp-wasm32@0.33.2':
    '@img/sharp-wasm32': private
  '@img/sharp-win32-ia32@0.33.2':
    '@img/sharp-win32-ia32': private
  '@img/sharp-win32-x64@0.33.2':
    '@img/sharp-win32-x64': private
  '@isaacs/cliui@8.0.2':
    '@isaacs/cliui': private
  '@pkgjs/parseargs@0.11.0':
    '@pkgjs/parseargs': private
  '@polka/url@0.5.0':
    '@polka/url': private
  '@protobufjs/aspromise@1.1.2':
    '@protobufjs/aspromise': private
  '@protobufjs/base64@1.1.2':
    '@protobufjs/base64': private
  '@protobufjs/codegen@2.0.4':
    '@protobufjs/codegen': private
  '@protobufjs/eventemitter@1.1.0':
    '@protobufjs/eventemitter': private
  '@protobufjs/fetch@1.1.0':
    '@protobufjs/fetch': private
  '@protobufjs/float@1.0.2':
    '@protobufjs/float': private
  '@protobufjs/inquire@1.1.0':
    '@protobufjs/inquire': private
  '@protobufjs/path@1.1.2':
    '@protobufjs/path': private
  '@protobufjs/pool@1.1.0':
    '@protobufjs/pool': private
  '@protobufjs/utf8@1.1.0':
    '@protobufjs/utf8': private
  '@telegraf/types@6.9.1':
    '@telegraf/types': private
  '@thi.ng/bitstream@2.2.46':
    '@thi.ng/bitstream': private
  '@thi.ng/errors@2.4.16':
    '@thi.ng/errors': private
  '@tokenizer/token@0.3.0':
    '@tokenizer/token': private
  '@types/body-parser@1.19.5':
    '@types/body-parser': private
  '@types/connect@3.4.38':
    '@types/connect': private
  '@types/express-serve-static-core@4.17.43':
    '@types/express-serve-static-core': private
  '@types/express@4.17.21':
    '@types/express': private
  '@types/http-errors@2.0.4':
    '@types/http-errors': private
  '@types/long@4.0.2':
    '@types/long': private
  '@types/mime@1.3.5':
    '@types/mime': private
  '@types/node-fetch@2.6.11':
    '@types/node-fetch': private
  '@types/node@18.19.15':
    '@types/node': private
  '@types/polka@0.5.7':
    '@types/polka': private
  '@types/qs@6.9.11':
    '@types/qs': private
  '@types/range-parser@1.2.7':
    '@types/range-parser': private
  '@types/send@0.17.4':
    '@types/send': private
  '@types/serve-static@1.15.5':
    '@types/serve-static': private
  '@types/trouter@3.1.4':
    '@types/trouter': private
  '@wasm-audio-decoders/common@9.0.5':
    '@wasm-audio-decoders/common': private
  '@wasm-audio-decoders/flac@0.2.4':
    '@wasm-audio-decoders/flac': private
  '@wasm-audio-decoders/ogg-vorbis@0.1.15':
    '@wasm-audio-decoders/ogg-vorbis': private
  '@whiskeysockets/baileys@6.6.0':
    '@whiskeysockets/baileys': private
  abort-controller@3.0.0:
    abort-controller: private
  agentkeepalive@4.5.0:
    agentkeepalive: private
  ansi-regex@5.0.1:
    ansi-regex: private
  ansi-styles@4.3.0:
    ansi-styles: private
  async@3.2.5:
    async: private
  asynckit@0.4.0:
    asynckit: private
  atomic-sleep@1.0.0:
    atomic-sleep: private
  audio-buffer@5.0.0:
    audio-buffer: private
  audio-decode@2.2.0:
    audio-decode: private
  audio-type@2.2.1:
    audio-type: private
  axios@1.6.7:
    axios: private
  balanced-match@1.0.2:
    balanced-match: private
  base-64@0.1.0:
    base-64: private
  body-parser@1.20.2:
    body-parser: private
  brace-expansion@2.0.1:
    brace-expansion: private
  buffer-alloc-unsafe@1.1.0:
    buffer-alloc-unsafe: private
  buffer-alloc@1.2.0:
    buffer-alloc: private
  buffer-fill@1.0.0:
    buffer-fill: private
  bytes@3.1.2:
    bytes: private
  cache-manager@4.0.1:
    cache-manager: private
  call-bind@1.0.6:
    call-bind: private
  charenc@0.0.2:
    charenc: private
  clone@2.1.2:
    clone: private
  codec-parser@2.4.3:
    codec-parser: private
  color-convert@2.0.1:
    color-convert: private
  color-name@1.1.4:
    color-name: private
  color-string@1.9.1:
    color-string: private
  color@4.2.3:
    color: private
  combined-stream@1.0.8:
    combined-stream: private
  content-type@1.0.5:
    content-type: private
  cross-spawn@7.0.3:
    cross-spawn: private
  crypt@0.0.2:
    crypt: private
  curve25519-js@0.0.4:
    curve25519-js: private
  debug@2.6.9:
    debug: private
  define-data-property@1.1.2:
    define-data-property: private
  delayed-stream@1.0.0:
    delayed-stream: private
  depd@2.0.0:
    depd: private
  destroy@1.2.0:
    destroy: private
  detect-libc@2.0.2:
    detect-libc: private
  digest-fetch@1.3.0:
    digest-fetch: private
  duplexify@4.1.2:
    duplexify: private
  eastasianwidth@0.2.0:
    eastasianwidth: private
  ee-first@1.1.1:
    ee-first: private
  emoji-regex@8.0.0:
    emoji-regex: private
  end-of-stream@1.4.4:
    end-of-stream: private
  es-errors@1.3.0:
    es-errors: private
  esbuild-android-64@0.15.18:
    esbuild-android-64: private
  esbuild-android-arm64@0.15.18:
    esbuild-android-arm64: private
  esbuild-darwin-64@0.15.18:
    esbuild-darwin-64: private
  esbuild-darwin-arm64@0.15.18:
    esbuild-darwin-arm64: private
  esbuild-freebsd-64@0.15.18:
    esbuild-freebsd-64: private
  esbuild-freebsd-arm64@0.15.18:
    esbuild-freebsd-arm64: private
  esbuild-linux-32@0.15.18:
    esbuild-linux-32: private
  esbuild-linux-64@0.15.18:
    esbuild-linux-64: private
  esbuild-linux-arm64@0.15.18:
    esbuild-linux-arm64: private
  esbuild-linux-arm@0.15.18:
    esbuild-linux-arm: private
  esbuild-linux-mips64le@0.15.18:
    esbuild-linux-mips64le: private
  esbuild-linux-ppc64le@0.15.18:
    esbuild-linux-ppc64le: private
  esbuild-linux-riscv64@0.15.18:
    esbuild-linux-riscv64: private
  esbuild-linux-s390x@0.15.18:
    esbuild-linux-s390x: private
  esbuild-netbsd-64@0.15.18:
    esbuild-netbsd-64: private
  esbuild-openbsd-64@0.15.18:
    esbuild-openbsd-64: private
  esbuild-sunos-64@0.15.18:
    esbuild-sunos-64: private
  esbuild-windows-32@0.15.18:
    esbuild-windows-32: private
  esbuild-windows-64@0.15.18:
    esbuild-windows-64: private
  esbuild-windows-arm64@0.15.18:
    esbuild-windows-arm64: private
  esbuild@0.15.18:
    esbuild: private
  event-target-shim@5.0.1:
    event-target-shim: private
  fast-redact@3.3.0:
    fast-redact: private
  file-type@16.5.4:
    file-type: private
  fluent-ffmpeg@2.1.2:
    fluent-ffmpeg: private
  follow-redirects@1.15.5:
    follow-redirects: private
  foreground-child@3.1.1:
    foreground-child: private
  form-data-encoder@1.7.2:
    form-data-encoder: private
  form-data@4.0.0:
    form-data: private
  formdata-node@4.4.1:
    formdata-node: private
  fsevents@2.3.3:
    fsevents: private
  function-bind@1.1.2:
    function-bind: private
  futoin-hkdf@1.5.3:
    futoin-hkdf: private
  get-intrinsic@1.2.4:
    get-intrinsic: private
  get-tsconfig@4.7.2:
    get-tsconfig: private
  glob@10.3.10:
    glob: private
  gopd@1.0.1:
    gopd: private
  has-property-descriptors@1.0.1:
    has-property-descriptors: private
  has-proto@1.0.1:
    has-proto: private
  has-symbols@1.0.3:
    has-symbols: private
  hasown@2.0.1:
    hasown: private
  http-errors@2.0.0:
    http-errors: private
  humanize-ms@1.2.1:
    humanize-ms: private
  iconv-lite@0.4.24:
    iconv-lite: private
  ieee754@1.2.1:
    ieee754: private
  inherits@2.0.4:
    inherits: private
  is-arrayish@0.3.2:
    is-arrayish: private
  is-buffer@1.1.6:
    is-buffer: private
  is-fullwidth-code-point@3.0.0:
    is-fullwidth-code-point: private
  isexe@2.0.0:
    isexe: private
  jackspeak@2.3.6:
    jackspeak: private
  libphonenumber-js@1.10.55:
    libphonenumber-js: private
  libsignal@https://codeload.github.com/adiwajshing/libsignal-node/tar.gz/11dbd962ea108187c79a7c46fe4d6f790e23da97:
    libsignal: private
  lodash.clonedeep@4.5.0:
    lodash.clonedeep: private
  long@5.2.3:
    long: private
  lru-cache@7.18.3:
    lru-cache: private
  matchit@1.1.0:
    matchit: private
  md5@2.3.0:
    md5: private
  media-typer@1.1.0:
    media-typer: private
  mime-db@1.52.0:
    mime-db: private
  mime-types@2.1.35:
    mime-types: private
  minimatch@9.0.3:
    minimatch: private
  minipass@7.0.4:
    minipass: private
  mpg123-decoder@0.4.12:
    mpg123-decoder: private
  mri@1.2.0:
    mri: private
  ms@2.0.0:
    ms: private
  music-metadata@7.14.0:
    music-metadata: private
  node-cache@5.1.2:
    node-cache: private
  node-domexception@1.0.0:
    node-domexception: private
  node-fetch@2.7.0:
    node-fetch: private
  node-wav@0.0.2:
    node-wav: private
  object-inspect@1.13.1:
    object-inspect: private
  ogg-opus-decoder@1.6.12:
    ogg-opus-decoder: private
  on-exit-leak-free@0.2.0:
    on-exit-leak-free: private
  on-finished@2.4.1:
    on-finished: private
  once@1.4.0:
    once: private
  opus-decoder@0.7.6:
    opus-decoder: private
  p-timeout@4.1.0:
    p-timeout: private
  path-key@3.1.1:
    path-key: private
  path-scurry@1.10.1:
    path-scurry: private
  peek-readable@4.1.0:
    peek-readable: private
  picocolors@1.0.0:
    picocolors: private
  pino-abstract-transport@0.5.0:
    pino-abstract-transport: private
  pino-std-serializers@4.0.0:
    pino-std-serializers: private
  pino@7.11.0:
    pino: private
  polka@0.5.2:
    polka: private
  process-warning@1.0.0:
    process-warning: private
  protobufjs@7.2.6:
    protobufjs: private
  proxy-from-env@1.1.0:
    proxy-from-env: private
  qoa-format@1.0.1:
    qoa-format: private
  qs@6.11.0:
    qs: private
  quick-format-unescaped@4.0.4:
    quick-format-unescaped: private
  raw-body@2.5.2:
    raw-body: private
  readable-stream@3.6.2:
    readable-stream: private
  readable-web-to-node-stream@3.0.2:
    readable-web-to-node-stream: private
  real-require@0.1.0:
    real-require: private
  resolve-pkg-maps@1.0.0:
    resolve-pkg-maps: private
  rimraf@5.0.5:
    rimraf: private
  safe-buffer@5.2.1:
    safe-buffer: private
  safe-compare@1.1.4:
    safe-compare: private
  safe-stable-stringify@2.4.3:
    safe-stable-stringify: private
  safer-buffer@2.1.2:
    safer-buffer: private
  sandwich-stream@2.0.2:
    sandwich-stream: private
  semver@7.6.0:
    semver: private
  set-function-length@1.2.1:
    set-function-length: private
  setprototypeof@1.2.0:
    setprototypeof: private
  sharp@0.33.2:
    sharp: private
  shebang-command@2.0.0:
    shebang-command: private
  shebang-regex@3.0.0:
    shebang-regex: private
  side-channel@1.0.5:
    side-channel: private
  signal-exit@4.1.0:
    signal-exit: private
  simple-swizzle@0.2.2:
    simple-swizzle: private
  simple-yenc@1.0.4:
    simple-yenc: private
  sonic-boom@2.8.0:
    sonic-boom: private
  split2@4.2.0:
    split2: private
  statuses@2.0.1:
    statuses: private
  stream-shift@1.0.3:
    stream-shift: private
  string-width@4.2.3:
    string-width-cjs: private
  string-width@5.1.2:
    string-width: private
  string_decoder@1.3.0:
    string_decoder: private
  strip-ansi@6.0.1:
    strip-ansi-cjs: private
  strip-ansi@7.1.0:
    strip-ansi: private
  strtok3@6.3.0:
    strtok3: private
  telegraf@4.15.3:
    telegraf: private
  thread-stream@0.15.2:
    thread-stream: private
  toidentifier@1.0.1:
    toidentifier: private
  token-types@4.2.1:
    token-types: private
  tr46@0.0.3:
    tr46: private
  trouter@2.0.1:
    trouter: private
  type-is@1.6.18:
    type-is: private
  undici-types@5.26.5:
    undici-types: private
  unpipe@1.0.0:
    unpipe: private
  util-deprecate@1.0.2:
    util-deprecate: private
  uuid@9.0.1:
    uuid: private
  web-streams-polyfill@3.3.2:
    web-streams-polyfill: private
  webidl-conversions@3.0.1:
    webidl-conversions: private
  whatwg-url@5.0.0:
    whatwg-url: private
  which@1.3.1:
    which: private
  wrap-ansi@7.0.0:
    wrap-ansi-cjs: private
  wrap-ansi@8.1.0:
    wrap-ansi: private
  wrappy@1.0.2:
    wrappy: private
  ws@8.16.0:
    ws: private
  yallist@4.0.0:
    yallist: private
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@9.1.0
pendingBuilds: []
prunedAt: Wed, 08 May 2024 02:11:02 GMT
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
registries:
  default: https://registry.npmjs.org/
skipped:
  - '@emnapi/runtime@0.45.0'
  - '@esbuild/aix-ppc64@0.19.12'
  - '@esbuild/android-arm64@0.19.12'
  - '@esbuild/android-arm@0.15.18'
  - '@esbuild/android-arm@0.19.12'
  - '@esbuild/android-x64@0.19.12'
  - '@esbuild/darwin-arm64@0.19.12'
  - '@esbuild/darwin-x64@0.19.12'
  - '@esbuild/freebsd-arm64@0.19.12'
  - '@esbuild/freebsd-x64@0.19.12'
  - '@esbuild/linux-arm64@0.19.12'
  - '@esbuild/linux-arm@0.19.12'
  - '@esbuild/linux-ia32@0.19.12'
  - '@esbuild/linux-loong64@0.15.18'
  - '@esbuild/linux-loong64@0.19.12'
  - '@esbuild/linux-mips64el@0.19.12'
  - '@esbuild/linux-ppc64@0.19.12'
  - '@esbuild/linux-riscv64@0.19.12'
  - '@esbuild/linux-s390x@0.19.12'
  - '@esbuild/linux-x64@0.19.12'
  - '@esbuild/netbsd-x64@0.19.12'
  - '@esbuild/openbsd-x64@0.19.12'
  - '@esbuild/sunos-x64@0.19.12'
  - '@esbuild/win32-arm64@0.19.12'
  - '@esbuild/win32-ia32@0.19.12'
  - '@ffmpeg-installer/darwin-arm64@4.1.5'
  - '@ffmpeg-installer/darwin-x64@4.1.0'
  - '@ffmpeg-installer/linux-arm64@4.1.4'
  - '@ffmpeg-installer/linux-arm@4.1.3'
  - '@ffmpeg-installer/linux-ia32@4.1.0'
  - '@ffmpeg-installer/linux-x64@4.1.0'
  - '@ffmpeg-installer/win32-ia32@4.1.0'
  - '@img/sharp-darwin-arm64@0.33.2'
  - '@img/sharp-darwin-x64@0.33.2'
  - '@img/sharp-libvips-darwin-arm64@1.0.1'
  - '@img/sharp-libvips-darwin-x64@1.0.1'
  - '@img/sharp-libvips-linux-arm64@1.0.1'
  - '@img/sharp-libvips-linux-arm@1.0.1'
  - '@img/sharp-libvips-linux-s390x@1.0.1'
  - '@img/sharp-libvips-linux-x64@1.0.1'
  - '@img/sharp-libvips-linuxmusl-arm64@1.0.1'
  - '@img/sharp-libvips-linuxmusl-x64@1.0.1'
  - '@img/sharp-linux-arm64@0.33.2'
  - '@img/sharp-linux-arm@0.33.2'
  - '@img/sharp-linux-s390x@0.33.2'
  - '@img/sharp-linux-x64@0.33.2'
  - '@img/sharp-linuxmusl-arm64@0.33.2'
  - '@img/sharp-linuxmusl-x64@0.33.2'
  - '@img/sharp-wasm32@0.33.2'
  - '@img/sharp-win32-ia32@0.33.2'
  - esbuild-android-64@0.15.18
  - esbuild-android-arm64@0.15.18
  - esbuild-darwin-64@0.15.18
  - esbuild-darwin-arm64@0.15.18
  - esbuild-freebsd-64@0.15.18
  - esbuild-freebsd-arm64@0.15.18
  - esbuild-linux-32@0.15.18
  - esbuild-linux-64@0.15.18
  - esbuild-linux-arm64@0.15.18
  - esbuild-linux-arm@0.15.18
  - esbuild-linux-mips64le@0.15.18
  - esbuild-linux-ppc64le@0.15.18
  - esbuild-linux-riscv64@0.15.18
  - esbuild-linux-s390x@0.15.18
  - esbuild-netbsd-64@0.15.18
  - esbuild-openbsd-64@0.15.18
  - esbuild-sunos-64@0.15.18
  - esbuild-windows-32@0.15.18
  - esbuild-windows-arm64@0.15.18
  - fsevents@2.3.3
  - tslib@2.6.2
storeDir: D:\.pnpm-store\v3
virtualStoreDir: D:\Downloads\Bot-whatsapp\Bot-whatsapp\node_modules\.pnpm
virtualStoreDirMaxLength: 120
